### PR TITLE
Maven central

### PR DESCRIPTION
**Pull request by lserveriiev**
The issue [630](https://github.com/9tigerio/db2rest/issues/630)

### CODE REVIEW

**Comment by thadguidry** [comment]
@lserveriiev take a look at my updates on #739 and #738.  I don't think GPG is necessary now according to Sonatype's docs?  We just need to pass in the 2 secrets which I've added to our GitHub `9tigerio` organization, which means they can be used in the CI/CD environment and are available to any collaborators, as shown in #738 

We should try to run the workflow.  Remember, `mvn deploy` already executes `mvn install` and `mvn build`, so no need for extra lines.  My workflow updates in #738 should "just work", I think.

**Comment by lserveriiev** [comment]
@thadguidry thank you for your comment. 

Don't we need to update the **distributionManagement.repository** in the **pom.xml**? 

I suspect adding a new profile can be skipped.

**Comment by lserveriiev** [comment]
@kdhrubo let's apply Thad's MRs and skip this MR.

**Comment by thadguidry** [comment]
@lserveriiev lolol, you can do that, but we'll still want you to fix up things after mine is merged. :-)  Because you rock!  Also, I likely didn't account for everything that we're eventually, ideally, going to need in the POM's, GitHub Action workflow, or who knows what.

**Review by kdhrubo — APPROVED** [review]

**Pull request merged**
