### PR TITLE
fix issues within application.yml file

### PR DESCRIPTION
**Pull request by thadguidry**
- escapes logging level keys that use special chars `.` , need to wrap with '[ ]'
- fix missing $ for variable

### CODE REVIEW

**Comment by kdhrubo** [comment]
why is this change needed?
Its working fine.

**Comment by thadguidry** [comment]
1. YAML map keys cannot contain special characters.  If DevOps processes try to grab the keys to change value, they will get failures (well, most yaml parsing libraries have an option to skip parse failures for map keys and be lenient a bit), but still, this can cause a bit of problem for folks doing custom application config changes during deployment.

2. The missing $ isn't a problem? it typically would be better to be consistent with variable replacement to have consistent syntax for variable placeholders.  That one is an outlier and not consistent with the other placeholders.  Why confuse automation programs and users?

**Comment by kdhrubo** [comment]
Line 19, missing $ is definitely a problem. 
The others which are package name essentially can be organized in hierarchy instead of '.' that should work.

**Comment by thadguidry** [comment]
You'd have to give an example for me in YAML what you mean.
Dotted keys are directly supported in TOML.

```toml
io.9tiger.server.id: booster
io.9tiger.server.ip: 127.0.0.1
```

Dots are even allowed in it's table (dictionaries) headers
```toml
[io.9tiger.server]
id: booster
ip: 127.0.0.1
```

**Comment by kdhrubo** [comment]
```logging:
  level:
    com: 
      homihq: 
       db2rest: 
         rest: INFO
```

**Review by kdhrubo — APPROVED** [review]

**Pull request merged**
