### PR TITLE
Add column information to database schema endpoint

### PR DESCRIPTION
**Pull request by carneytyler**
Before:

```json
{
  "schema": "public",
  "name": "django_migrations",
  "type": "TABLE"
}
```

After:

```json
{
  "schema": "public",
  "name": "django_migrations",
  "type": "TABLE",
  "columns": [
    {
      "name": "id",
      "pk": true,
      "dataType": "int4"
    },
    {
      "name": "app",
      "pk": false,
      "dataType": "varchar"
    },
    {
      "name": "name",
      "pk": false,
      "dataType": "varchar"
    },
    {
      "name": "applied",
      "pk": false,
      "dataType": "timestamptz"
    }
  ]
}
```

### CODE REVIEW

**Comment by thadguidry** [comment]
I feel like maybe this should be something opt-in, maybe through a config preference?
What do you think @carneytyler ?

**Comment by kdhrubo** [comment]
Yes good point. Can be a request param

**Comment by carneytyler** [comment]
@thadguidry @kdhrubo this is now a URL param `columns` defaulting to `False` with updated testing. Hopefully it all looks good!

**Comment by kdhrubo** [comment]
👍.

**Pull request merged**
